version: '3.9'

services:
  db:
    image: postgres:bullseye
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: trucks_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: db
    networks:
      - network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - network
    environment:
      - POSTGRES_DB=trucks_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    command: /code/django.sh
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  network:
    driver: bridge
